// src/components/Practice.svelte
<script lang="ts">
  import { onMount } from "svelte";
  let isMounted = false;

  onMount(() => {
    isMounted = true;
  });

  import ChipExercise from "./ChipExercise.svelte";
  import { KALAMA } from "@/consts";
  import { verifyChips, type Exercise } from "@/utils/exercise";

  export let exercises: Exercise[];
  export let locale: Record<string, string>;

  const _ = (text: string) => locale[text];

  let exerciseQueue: Exercise[] = [...exercises];
  let currentIndex = 0;
  let completed = 0;
  let assembledSentence: string[] = [];
  let statusMessage: string | null = null;
  let checked = false;
  let allDone = false;

  let sfx_yes: HTMLAudioElement | null = null;
  let sfx_no: HTMLAudioElement | null = null;
  let sfx_done: HTMLAudioElement | null = null;

  let currentExercise: Exercise;

  onMount(() => {
    if (typeof Audio !== "undefined") {
      sfx_yes = new Audio(`${KALAMA}/sfx/yes.mp3`);
      sfx_no = new Audio(`${KALAMA}/sfx/no.mp3`);
      sfx_done = new Audio(`${KALAMA}/sfx/done.mp3`);
    }
  });

  $: currentExercise = exerciseQueue[currentIndex];

  function handleCheck() {
    completed += 1;

    if (verifyChips(currentExercise, assembledSentence)) {
      statusMessage = _("correct");
      sfx_yes?.play();
    } else {
      statusMessage = `${_("incorrect")} "${currentExercise.l2}"`;
      exerciseQueue = [...exerciseQueue, exerciseQueue[currentIndex]];
      sfx_no?.play();
    }

    checked = true;
  }

  function handleContinue() {
    if (currentIndex < exerciseQueue.length - 1) {
      currentIndex += 1;
      assembledSentence = [];
      statusMessage = null;
      checked = false;
    } else {
      allDone = true;
      sfx_done?.play();
    }
  }
</script>

{#if isMounted}
  <div class="exercise">
    <div class="progress-container">
      <div
        class="progress"
        style="width: {(completed / exerciseQueue.length) * 100}%"
      ></div>
    </div>

    {#if allDone}
      <h2>{_("done")}</h2>
    {:else}
      <h2>{_("translate")}</h2>
      <h3>{currentExercise.l1}</h3>

      <ChipExercise
        exercise={currentExercise}
        setAssembledSentence={(words: string[]) => (assembledSentence = words)}
        locked={checked}
      />

      <div class="footer">
        <button
          on:click={checked ? handleContinue : handleCheck}
          class="button"
        >
          {checked ? _("continue") : _("check")}
        </button>
        {#if statusMessage}
          <p>{statusMessage}</p>
        {/if}
      </div>
    {/if}
  </div>
{:else}
  <noscript>
    This interactive practice game needs Javascript to run, sorry!
  </noscript>
{/if}

<style>
  .exercise {
    padding: 20px;
    /* max-width: 600px; */
    margin: auto;
  }
  .progress-container {
    height: 20px;
    border: 1px solid var(--grey);
    background-color: var(--bg-2);
    border-radius: 10px;
  }
  .progress {
    height: 20px;
    border-radius: 10px;
    background-color: var(--accent);
    transition: width 0.5s ease;
  }
  .footer {
    display: flex;
    gap: 10px;
    align-items: center;
  }
  .footer p {
    margin: 0;
  }
  .button {
    display: inline-block;
    background-color: var(--bg-2);
    padding: 10px 17px;
    border-radius: 15px;
    border: 1px solid var(--grey-1);
    box-shadow: 0px 2px var(--grey-1);
    margin: 4px;
    cursor: pointer;
    user-select: none;
    font-size: 125%;
    font-family: inherit;
    min-width: 20%;
    flex-shrink: 0;
  }
</style>

// src/components/Practice.tsx
import ChipExercise from "@/components/ChipExercise.tsx";
import { KALAMA } from "@/consts";
import { verifyChips, type Exercise } from "@/utils/exercise";
import React, { useState } from "react";

const Practice: React.FC<{
  exercises: Exercise[];
  locale: Record<string, string>;
}> = ({ exercises, locale }) => {
  const _ = (text: string) => locale[text];
  const [exerciseQueue, setExerciseQueue] = useState<Exercise[]>(exercises);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [completed, setCompleted] = useState(0);
  const [assembledSentence, setAssembledSentence] = useState<string[]>([]);
  const [statusMessage, setStatusMessage] = useState<string | null>(null);
  const [checked, setChecked] = useState(false);
  const [allDone, setAllDone] = useState(false);

  const currentExercise = exerciseQueue[currentIndex];

  // Audio doesn't exist server-side, this is a wrapper to avoid that
  const [sfx_yes] = useState(
    typeof Audio !== "undefined" && new Audio(`${KALAMA}/sfx/yes.mp3`),
  );
  const [sfx_no] = useState(
    typeof Audio !== "undefined" && new Audio(`${KALAMA}/sfx/no.mp3`),
  );
  const [sfx_done] = useState(
    typeof Audio !== "undefined" && new Audio(`${KALAMA}/sfx/done.mp3`),
  );

  const handleCheck = () => {
    setCompleted(completed + 1);
    if (verifyChips(currentExercise, assembledSentence)) {
      setStatusMessage(_("correct"));
      sfx_yes.play();
    } else {
      setStatusMessage(`${_("incorrect")} "${currentExercise.l2}"`);
      setExerciseQueue((prev) => [...prev, prev[currentIndex]]);
      sfx_no.play();
    }
    setChecked(true);
  };

  const handleContinue = () => {
    if (currentIndex < exerciseQueue.length - 1) {
      setCurrentIndex(currentIndex + 1);
      setAssembledSentence([]);
      setStatusMessage(null);
      setChecked(false);
    } else {
      setAllDone(true);
      sfx_done.play();
    }
  };

  return (
    <div className="exercise">
      <div className="exercise-progress-container">
        <div
          className="exercise-progress"
          style={{ width: `${(completed / exerciseQueue.length) * 100}%` }}
        ></div>
      </div>
      {allDone ? (
        <h2>{_("done")}</h2>
      ) : (
        <>
          <h2>{_("translate")}</h2>
          <h3>{currentExercise.l1}</h3>
          <ChipExercise
            exercise={currentExercise}
            onAssembledSentenceChange={setAssembledSentence}
            locked={checked}
          />
          <div className="exercise-footer">
            <button
              onClick={checked ? handleContinue : handleCheck}
              className="exercise-button chip"
            >
              {checked ? _("continue") : _("check")}
            </button>
            {statusMessage && <p>{statusMessage}</p>}
          </div>
        </>
      )}
    </div>
  );
};

export default Practice;
